### ISSUE TITLE
On Voicemith

### ISSUE THREAD

**Issue by mahalisyarifuddin** [claire-west/svstudio-guides#1]
Oh hi. SynthV Fandom Wiki contributor here.

Really appreciate the guide you made.

Just to inform you that [Voicemith's ECPay storefront](https://voicemithshop.cashier.ecpay.com.tw) only works for those in Taiwan, and international buyers are prompted to purchase on [their site](http://www.voicemith.com/6084-2) so that people can use PayPal/credit/debit (only digital copy though). ([more on that on this tweet](https://twitter.com/YuyaoOfficial/status/1615903102913376261))

Would be great if you put a notice regarding this to your guide.

Thank you.

**Comment by cv4x** [comment]
Thanks for the heads-up, it's been corrected.
