### ISSUE TITLE
on Koharu Rikka's name

### ISSUE THREAD

**Issue by leanneubaldo** [claire-west/svstudio-guides#5]
Hello Claire! I'm a follower of the Neocities site and I appreciate your efforts in compiling all of these information on SynthV. 

Just want to inform you that Koharu Rikka's Japanese name is not "小春六夏", but "**小春六花**". IIRC, The TOKYO6 girls all have the "花" character in their names, and perhaps that "夏" typo came from "Natsu"-ki Karin's name. I've seen this typo in all places in the website where Koharu Rikka's name is present. 

Would appreciate it if you fix it soon. Thank you!

**Comment by cv4x** [comment]
Oh, good catch. Yeah it certainly doesn't make sense to have "Summer" in the Spring girl's name, must've been some sort of copy-paste error.

Thanks for letting me know!
